name: Pytest and Coverage

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master

jobs:
  pytest:
    name: Pytest and Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
      with:
        python-version: '3.13'    # or match your `.python-version`

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
      with:
        activate-environment: true

    - name: Run pytest
      run: PYTHONPATH=. uv run --no-default-groups --group test --group schema --frozen coverage run -m pytest

    - name: Run coverage
      run: PYTHONPATH=. uv run --no-default-groups --group test --group schema --frozen coverage report -m --fail-under=100
