name: Pytest and Coverage

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master

jobs:
  pytest:
    name: Pytest and Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.13'    # or match your `.python-version`

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@94527f2e458b27549849d47d273a16bec83a01e9
      with:
        activate-environment: true

    - name: Run pytest
      run: PYTHONPATH=. uv run --no-default-groups --group test --group schema --frozen coverage run -m pytest

    - name: Run coverage
      run: PYTHONPATH=. uv run --no-default-groups --group test --group schema --frozen coverage report -m --fail-under=100
