# This workflow will upload the package to PyPi when a release is created
# It uses the trusted publisher authentication model, no more secrets and api keys

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
      with:
        activate-environment: true

    - name: Build package
      run: uv build
    - name: Check package metadata
      run: uvx twine check dist/*

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
      with:
        verbose: true
