# This workflow will upload the package to PyPi when a release is created
# It uses the trusted publisher authentication model, no more secrets and api keys

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@94527f2e458b27549849d47d273a16bec83a01e9
      with:
        activate-environment: true

    - name: Build package
      run: uv build
    - name: Check package metadata
      run: uvx twine check dist/*

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
      with:
        verbose: true
